### PR TITLE
Update register site design

### PR DESCRIPTION
**Pull request by nkarmi**
- Add CeraCY font
- Update button style
- Update value field style
- Update label style
- Update help text style
- Update home page style

### CODE REVIEW

**Comment by nkarmi** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;RypILcOz&#x2F;751-0-25-reg-ui-update-buttons-style-cycle-18"> (0.25) REG - UI - Update buttons style [Cycle 18]</a>

**Comment by nkarmi** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;hf62Z3rs&#x2F;753-0-25-reg-ui-update-field-values-style-cycle-18"> (0.25) REG - UI - Update field values style [Cycle 18]</a>

**Comment by nkarmi** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;mWxWDQUC&#x2F;761-0-25-reg-ui-update-login-page-style-cycle-18"> (0.25) REG - UI - Update login page style [Cycle 18]</a>

**Comment by nkarmi** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;vzKBVvST&#x2F;752-0-25-reg-ui-update-field-labels-style-cycle-18"> (0.25) REG - UI - Update field labels style [Cycle 18]</a>

**Comment by nkarmi** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;k3P52Tsg&#x2F;749-0-25-reg-ui-update-radio-buttons-style-cycle-18"> (0.25) REG - UI - Update radio buttons style [Cycle 18]</a>

**Comment by nkarmi** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;7xV31HlV&#x2F;750-0-25-reg-ui-update-checkboxes-style-cycle-18"> (0.25) REG - UI - Update checkboxes style [Cycle 18]</a>

**Comment by nkarmi** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;veeR9vlC&#x2F;754-0-25-reg-ui-update-fonts-for-register-elements-cycle-18"> (0.25) REG - UI - Update fonts for register elements [Cycle 18]</a>

**Comment by nkarmi** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;enoteoaI&#x2F;756-0-25-reg-ui-fix-modal-dimensions-for-license-id-and-ssn-cycle-18"> (0.25) REG - UI - Fix modal dimensions for license ID and SSN [Cycle 18]</a>

**Comment by nkarmi** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;0tocxO1m&#x2F;758-1-reg-ui-update-email-next-of-kin-page-and-done-page-cycle-18"> (1) REG - UI - Update email next of kin page and done page [Cycle 18]</a>

**Comment by nkarmi** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;2S3RDqwn&#x2F;755-0-25-reg-ui-build-social-share-modal-for-sharing-to-facebook-and-twitter-cycle-18"> (0.25) REG - UI - Build social share modal for sharing to Facebook and Twitter [Cycle 18]</a>

**Comment by nkarmi** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;1XLgAhtW&#x2F;748-0-25-reg-ui-update-progress-bar-style-cycle-18"> (0.25) REG - UI - Update progress bar style [Cycle 18]</a>

**Comment by nkarmi** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;g2t9DxFG&#x2F;757-0-25-reg-ui-change-fields-order-in-personal-information-form-cycle-18"> (0.25) REG - UI - Change fields order in personal information form [Cycle 18]</a>

**Comment by nkarmi** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;sCCwwPt1&#x2F;852-0-25-reg-ui-add-map-image-depends-on-active-state-cycle-18"> (0.25) REG - UI - Add map image depends on active state [Cycle 18]</a>

**Comment by nkarmi** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;S6KbMwOs&#x2F;854-0-25-reg-update-register-terms-and-conditions-text-and-change-the-style-for-first-line"> (0.25) REG - Update register terms and conditions text and change the style for first line</a>

**Comment by nkarmi** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;QJeC6WEP&#x2F;867-0-25-reg-send-button-in-next-of-kin-email-page-is-not-functional-cycle-18"> (0.25) REG - send button in next of kin email page is not functional [Cycle 18]</a>

**Comment by nkarmi** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;BJBXOw9t&#x2F;868-1-reg-non-field-errors-are-not-being-displayed-in-start-page-form-cycle-18"> (1) REG - Non Field Errors are not being displayed in Start page form [Cycle 18]</a>

**Comment by nkarmi** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;byRMpAi0&#x2F;865-0-25-reg-next-of-kin-email-body-text-still-need-to-be-updated-cycle-18"> (0.25) REG - next of kin email body text still need to be updated [Cycle 18]</a>

**Comment by nkarmi** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;pHCNLSy4&#x2F;866-0-25-reg-revoke-my-registration-page-display-html-tags-cycle-18"> (0.25) REG - Revoke my registration page _ display html tags [Cycle 18]</a>

**Comment by nkarmi** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;RG13osgO&#x2F;874-0-25-reg-buttons-text-need-to-be-centered-cycle-18"> (0.25) REG _ buttons text need to be centered [Cycle 18]</a>

**Comment by nkarmi** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;xy8JaWT4&#x2F;873-0-25-reg-revocation-update-fonts-fields-buttons-to-match-the-registration-flow-pages-styles-cycle-18"> (0.25) REG - Revocation - Update fonts&#x2F;fields&#x2F;buttons to match the registration flow pages styles. [Cycle 18]</a>

**Comment by nkarmi** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;sa7d31yH&#x2F;872-1-reg-update-registration-update-fonts-fields-buttons-to-match-the-registration-flow-pages-styles-cycle-18"> (1) REG - Update Registration - Update fonts&#x2F;fields&#x2F;buttons to match the registration flow pages styles. [Cycle 18]</a>

**Comment by nkarmi** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;W1xRUPUq&#x2F;877-0-25-reg-agree-to-terms-of-service-ie"> (0.25) REG - agree to Terms of Service - IE</a>

**Comment by nkarmi** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;vy6i6wVn&#x2F;869-0-25-reg-nok-make-the-email-text-area-un-resizable-and-add-auto-scrolling-cycle-18"> (0.25) REG - NOK - Make the email text area un-resizable, and add auto scrolling. [Cycle 18]</a>

**Comment by nkarmi** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;4XM5WAQ9&#x2F;879-0-25-reg-small-mobile-screen-display-issues-cycle-18"> (0.25) REG - small mobile screen display issues [Cycle 18]</a>

**Comment by waseem-omar** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;P1TJyi1p&#x2F;895-0-25-reg-ui-when-translating-to-spanish-the-donation-preferences-checkboxes-displays-differently-cycle-18"> (0.25) REG - UI - When translating to Spanish, the donation preferences checkboxes displays differently [Cycle 18]</a>

**Comment by waseem-omar** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;iVfp7bB5&#x2F;896-0-25-reg-state-name-is-missing-when-user-is-viewing-the-website-in-espanol-cycle-18"> (0.25) REG - state name is missing when user is viewing the website in Español [Cycle 18]</a>

**Comment by nkarmi** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;qXe2M5DA&#x2F;899-0-25-reg-personal-info-page-postal-code-espanol"> (0.25) REG - personal info page -postal code - Español</a>

**Comment by nkarmi** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;uV9HVFM6&#x2F;898-0-25-reg-revoke-my-registration-page-still-has-some-text-need-to-be-translated-cycle-18"> (0.25) REG - Revoke my registration page still has some text need to be translated [Cycle 18]</a>

**Comment by nkarmi** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;KEFarapf&#x2F;900-0-25-reg-twitter-pic-ie-cycle-18"> (0.25) REG -twitter pic - IE [Cycle 18]</a>

**Comment by nkarmi** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;W6zXgdr2&#x2F;901-0-25-reg-licence-id-modal-espanol-cycle-18"> (0.25) REG - licence ID modal - Español [Cycle 18]</a>

**Comment by nkarmi** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;JZMIfvhI&#x2F;904-0-25-reg-ui-update-minor-page-style-cycle-19"> (0.25) REG - UI - Update minor page style [Cycle 19]</a>

**Comment by nkarmi** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;87axMmqZ&#x2F;903-0-25-reg-revoke-my-registration-button-mouse-hover-in-mobile-cycle-19"> (0.25) REG - Revoke my registration button - mouse hover in mobile [Cycle 19]</a>

**Comment by nkarmi** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;ZmBYYKsA&#x2F;930-0-25-reg-update-cera-font-included-in-register-cycle-19"> (0.25) REG - Update Cera font included in Register [Cycle 19]</a>

**Comment by nkarmi** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;fIp0F0xD&#x2F;932-0-25-reg-mobile-site-has-non-terminated-html-causing-it-to-scroll-left-and-right-by-a-few-pixels-cycle-19"> (0.25) REG - mobile site has non-terminated html causing it to scroll left and right by a few pixels [Cycle 19]</a>

**Comment by nkarmi** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;hNcU4z3i&#x2F;862-reg-bug-in-twitter-share-word-counting-cycle-18-cycle-19"> REG - Bug in twitter share word counting [Cycle 18] [Cycle 19]</a>

**Comment by nkarmi** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;qQnDkuhN&#x2F;941-0-25-reg-add-missing-text-translations-cycle-20"> (0.25) REG - Add missing text translations [Cycle 20]</a>

**Pull request merged**
